requires 'Mojolicious::Lite';
requires 'Minion' => '10.28';
requires 'Minion::Notifier';
requires 'Net::Statsd::Client';
requires 'Mojo::Pg';
requires 'Path::Tiny';
requires 'WWW::Google::Cloud::Auth::ServiceAccount';
requires 'LWP::Protocol::https';
requires 'DateTime';
