[project]
name = "prop-renderer"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
matplotlib = "3.9.2"
cartopy = "0.23.0"
pandas = "*"
h5py = "3.7.0"
hdf5plugin = "4.1.1"
scipy = "*"
pykdtree = "*"
uwsgi = "*"
flask = "2.2.*"

[pypi-dependencies]
geojsoncontour = "~=0.4.0"
